server:
  port: 8090
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.134.148:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true